### ISSUE TITLE
Intermittent crashes

### ISSUE THREAD

**Issue by HenryBaby** [A-tG/VoicemeeterFancyOSD#25]
I am not sure how to reproduce this issue, but it happens to me at least a couple of times per day.

```
---------------------------
VoicemeeterFancyOSD
---------------------------
PRESS Ctrl + C TO COPY THIS TEXT
Unhandled exception:
 Insufficient memory to continue the execution of the program.    at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()

   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)

   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)

   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)

   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
---------------------------
OK   
---------------------------
```

**Comment by A-tG** [comment]
It is some kind of WPF internal render failure. May be related to bad GPU driver, insufficient VRAM. You can monitor VRAM usage in Task Manager: click on the bottom 'More Details' -> 'Details' tab -> Right Click on columns -> Select columns -> Check 'Dedicated GPU memory'. In my case it's around 18-19 K. [You may also disable hardware acceleration for WPF globally](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/graphics-rendering-registry-settings?view=netframeworkdesktop-4.8#disable-hardware-acceleration-option)

**Comment by A-tG** [comment]
I've added option to disable hardware acceleration in new version. It's not optimal but it should help in similar cases. And, yeah, it most likely OS/GPU/gpu-driver problem. As far as I know discrete GPU may be using RAM as VRAM and maybe at some there is not enough free memory.

**Comment by HenryBaby** [comment]
Yeah, I agree. You can close this issue I think. I'll look around for other solutions, seems the problem seems to be somewhere else.

**Comment by HenryBaby** [comment]
I've tried the latest release, running on SoftwareOnly, and so far I can't reproduce the issue, which makes me happy of course!

But it would be cool to be able to fix the original issue, since I assume this might happen with other tools in the future. Thank's for the quick fix!

**Comment by HenryBaby** [comment]
Just wanted to give a small update. The driver failure/memory failure(?) still happens, the only thing that is fixed in 0.13.0.0 is that if RenderMode is set to SoftwareOnly the program no longer crashes during the failure. Coincidentally if I don't run the program, I can't reproduce the issue at all.

I am currently in the process of testing older versions to see if a specific change might be the root cause.
